version: '3.9'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${DB_PORT}

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh /app/wsgi-entrypoint.sh
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 8000:8000
